# GoReleaser 配置文件 - 仅 Windows 版本
# 用于在 Windows 系统上只构建 Windows 版本

version: 2

project_name: topology

# 构建前钩子（生成 Windows 图标/清单的 .syso，使 exe 带图标）
before:
  hooks:
    - go mod tidy
    - go install github.com/tc-hib/go-winres@latest
    - go-winres make

# 构建配置 - 仅 Windows
builds:
  - id: windows
    main: .
    binary: topology
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    # 构建标签 - 与 Makefile build-windows 一致（WebView2 embed）
    tags:
      - exp_gowebview2loader
    ldflags:
      - -s -w
      - -H=windowsgui
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildTime={{.Date}}

# 归档配置
archives:
  - id: windows
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - zip
    files:
      - LICENSE
      - README.md

# 校验和配置（文件名含 Os、Arch，使用 Runtime.Goos/Goarch）
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_Windows_checksums.txt"
  algorithm: sha256

# 快照配置
snapshot: {}

# Changelog配置
changelog:
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^update:"
