// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExportData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportData'](arg1, arg2, arg3, arg4);
}

export function FormatSQL(arg1) {
  return window['go']['main']['App']['FormatSQL'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetTableData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTableSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateTableData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTableData'](arg1, arg2, arg3, arg4);
}
