// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSQL(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeSQL'](arg1, arg2);
}

export function ClearQueryHistory() {
  return window['go']['main']['App']['ClearQueryHistory']();
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExportData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportData'](arg1, arg2, arg3, arg4, arg5);
}

export function FormatSQL(arg1) {
  return window['go']['main']['App']['FormatSQL'](arg1);
}

export function GenerateCreateTableSQL(arg1, arg2) {
  return window['go']['main']['App']['GenerateCreateTableSQL'](arg1, arg2);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetDatabases(arg1, arg2) {
  return window['go']['main']['App']['GetDatabases'](arg1, arg2);
}

export function GetExecutionPlan(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetExecutionPlan'](arg1, arg2, arg3);
}

export function GetQueryHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetQueryHistory'](arg1, arg2, arg3);
}

export function GetSchemaMetadata(arg1) {
  return window['go']['main']['App']['GetSchemaMetadata'](arg1);
}

export function GetSnippets() {
  return window['go']['main']['App']['GetSnippets']();
}

export function GetTableData(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetTableSchema(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2, arg3, arg4);
}

export function GetTables(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTables'](arg1, arg2, arg3);
}

export function ImportData(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ImportData'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ImportDataPreview(arg1, arg2) {
  return window['go']['main']['App']['ImportDataPreview'](arg1, arg2);
}

export function ImportNavicatConnections(arg1) {
  return window['go']['main']['App']['ImportNavicatConnections'](arg1);
}

export function ImportNavicatConnectionsFromDialog() {
  return window['go']['main']['App']['ImportNavicatConnectionsFromDialog']();
}

export function LoadSchemaMetadata(arg1) {
  return window['go']['main']['App']['LoadSchemaMetadata'](arg1);
}

export function ReconnectConnection(arg1) {
  return window['go']['main']['App']['ReconnectConnection'](arg1);
}

export function ReleaseSession(arg1, arg2) {
  return window['go']['main']['App']['ReleaseSession'](arg1, arg2);
}

export function SaveSnippet(arg1, arg2) {
  return window['go']['main']['App']['SaveSnippet'](arg1, arg2);
}

export function StartMonitor(arg1) {
  return window['go']['main']['App']['StartMonitor'](arg1);
}

export function StopMonitor(arg1) {
  return window['go']['main']['App']['StopMonitor'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function UpdateTableData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTableData'](arg1, arg2, arg3, arg4, arg5);
}
