// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<string>;

export function ExportData(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FormatSQL(arg1:string):Promise<string>;

export function GetConnections():Promise<string>;

export function GetTableData(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function GetTableSchema(arg1:string,arg2:string):Promise<string>;

export function GetTables(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function TestConnection(arg1:string):Promise<boolean>;

export function UpdateTableData(arg1:string,arg2:string,arg3:string):Promise<void>;
